config/routes.rb
Rails.application.routes.draw do
  get 'static/home'
  root to: "static#home"

  resource :room, only: [:show, :new, :edit, :create, :update]

  resource :game, only: [:show, :new, :create]

  resource :player, only: [:destroy]

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :room
  has_many :players, through: :room
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :room, optional: true
  has_many :games, through: :room

  validates :name, presence: true, allow_blank: false
end

app/models/room.rb
class Room < ApplicationRecord
  require 'yaml'

  has_many :players
  has_many :games

  before_create :set_access_token

  def set_access_token
    self.token = generate_token
  end

  def generate_token
    loop do
      slang = YAML.load_file('lib/assets/slang.yml')
      token = slang['slang'].sample()
                            .downcase
                            .tr(' ', '-') + '-' + rand(9999).to_s
      break token unless Room.where(token: token).exists?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_player, :current_room, :authorized_player?

  def current_player
    @current_player = session[:current_player_id] &&
      Player.find(session[:current_player_id])
  end

  def current_room
    @room = Room.find_by(token: token)
  end

  def authorized_player?
    current_room.players.ids.include?(session[:current_player_id])
  end

  private

  def token
    params[:token]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    #create a game
  end

  def show

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def destroy
    @room = current_player.room
    current_player.destroy

    ActionCable.server.broadcast 'room_channel',
      players: @room.players.pluck(:name)

    redirect_to static_home_path
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    if authorized_player?
      @player_names = current_room.players.pluck(:name)
      ActionCable.server.broadcast 'room_channel',
        players: @player_names
    else
      redirect_to edit_room_path(token: token)
    end
  end

  def new
  end

  def edit
    @token = token
  end

  def create
    player = Player.new(player_params)

    if player.save
      room = Room.create
      player.update_attributes(room_id: room.id)
      session[:current_player_id] = player.id

      redirect_to action: 'show', token: room.token
    else
      render :new
    end
  end

  def update
    room = Room.find_by(room_params)
    player = Player.new(player_params)

    if room.present? && player.save
      player.update_attributes(room_id: room.id)
      session[:current_player_id] = player.id

      redirect_to action: 'show', token: room.token
    else
      render :edit
    end
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end

  def room_params
    params.require(:player).permit(:token)
  end

  def token
    params[:token]
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blind Tiger</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/edit.html.erb
<div class='main-content'>
  <div class='main-menu'>
    <h1>Blind Tiger</h1>
  </div>

  <hr>

  <div class='edit-room'>
    <%= form_for :player, url: room_path, method: :put do |f| %>

      <div class='input-form-container mbl'>
        <%= f.text_field :token,
          class: 'form-control',
          placeholder: 'Enter an access code',
          value: @token %>

        <br>

        <%= f.text_field :name,
          class: 'form-control',
          placeholder: 'Enter your name' %>
      </div>

      <br>

      <div class='button-container'>
        <%= f.submit 'Join', class: 'btn btn-simple' %>
        <%= link_to 'Back', static_home_path, method: 'get', class: 'btn btn-simple' %>
      </div>

    <% end %>

  </div>
</div>

app/views/rooms/join.html.erb
<h1>Room#edit</h1>
<p>Find me in app/views/room/edit.html.erb</p>

app/views/rooms/new.html.erb
<div class='main-content'>
  <div class='main-menu'>
    <h1>Blind Tiger</h1>
  </div>

  <hr>

  <div class='create-room'>
    <%= form_for :player, url: room_path, method: :post do |f| %>

      <div class='input-form-container mbl'>
        <%= f.text_field :name,
          class: 'form-control',
          placeholder: 'Enter your name' %>
      </div>

      <br>

      <div class='button-container'>
        <%= f.submit 'Create', class: 'btn btn-simple' %>
        <%= link_to 'Back', static_home_path, method: 'get', class: 'btn btn-simple' %>
      </div>

    <% end %>

  </div>
</div>

app/views/rooms/show.html.erb
<h4>Waiting For Players...</h4>
<p>Access Code: <%= @room.token %></p>
<hr>

<div class='js-player-names'>
  <%- @player_names.each_with_index do |name, index| %>
    <p class='js-player-name'>
      <b><%= index + 1 %></b> <%= name %>
    </p>
  <% end %>
</div>

<hr>

<div class='button-container'>
  <%= button_to 'Start Game', game_path, method: 'post', class: 'btn btn-simple' %>
  <%= button_to 'Leave Game', player_path, method: 'delete', class: 'btn btn-simple' %>
</div>